// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  /**
   * See https://developer.chrome.com/docs/extensions/reference/i18n/#method-getMessage
   */
  interface GetMessageOptions {
    /**
     * See https://developer.chrome.com/docs/extensions/reference/i18n/#method-getMessage
     */
    escapeLt?: boolean
  }

  export interface WxtI18n extends I18n.Static {
    /**
     * The extension or app ID; you might use this string to construct URLs for resources inside the extension. Even unlocalized extensions can use this message.
     * Note: You can't use this message in a manifest file.
     *
     * "<browser.runtime.id>"
     */
    getMessage(
      messageName: "@@extension_id",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "<browser.i18n.getUiLocale()>"
     */
    getMessage(
      messageName: "@@ui_locale",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * The text direction for the current locale, either "ltr" for left-to-right languages such as English or "rtl" for right-to-left languages such as Japanese.
     *
     * "<ltr|rtl>"
     */
    getMessage(
      messageName: "@@bidi_dir",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * If the @@bidi_dir is "ltr", then this is "rtl"; otherwise, it's "ltr".
     *
     * "<rtl|ltr>"
     */
    getMessage(
      messageName: "@@bidi_reversed_dir",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * If the @@bidi_dir is "ltr", then this is "left"; otherwise, it's "right".
     *
     * "<left|right>"
     */
    getMessage(
      messageName: "@@bidi_start_edge",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * If the @@bidi_dir is "ltr", then this is "right"; otherwise, it's "left".
     *
     * "<right|left>"
     */
    getMessage(
      messageName: "@@bidi_end_edge",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * The extension title shown in the toolbar and popup.
     *
     * "Ophelia"
     */
    getMessage(
      messageName: "actionTitle",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Heading for the popup connection settings section.
     *
     * "Connection"
     */
    getMessage(
      messageName: "connectionLabel",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Label showing the default Ophelia port.
     *
     * "default: $PORT$"
     */
    getMessage(
      messageName: "defaultPortLabel",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Label for the global interception toggle.
     *
     * "Intercept downloads"
     */
    getMessage(
      messageName: "enabledLabel",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * The extension description shown in browser extension management UIs.
     *
     * "Intercept downloads and send them to Ophelia"
     */
    getMessage(
      messageName: "extDescription",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * The localized extension name.
     *
     * "Ophelia"
     */
    getMessage(
      messageName: "extName",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Fallback error shown when the popup cannot initialize.
     *
     * "Couldn't load the popup. Check the extension console for details."
     */
    getMessage(
      messageName: "loadError",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Label for the Ophelia port input.
     *
     * "Port"
     */
    getMessage(
      messageName: "portLabel",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Helper text shown below the port setting.
     *
     * "Only change this if you changed Ophelia's port."
     */
    getMessage(
      messageName: "popupWarningMatch",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Label for the save button.
     *
     * "Save"
     */
    getMessage(
      messageName: "saveButton",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Confirmation message shown after saving settings.
     *
     * "Saved"
     */
    getMessage(
      messageName: "saveFeedback",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Status shown while testing the Ophelia connection.
     *
     * "Checking…"
     */
    getMessage(
      messageName: "statusChecking",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Status shown when Ophelia is reachable.
     *
     * "Connected"
     */
    getMessage(
      messageName: "statusConnected",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * Status shown when Ophelia is unreachable.
     *
     * "Not running"
     */
    getMessage(
      messageName: "statusNotRunning",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    getMessage(
      messageName: "@@extension_id" | "@@ui_locale" | "@@bidi_dir" | "@@bidi_reversed_dir" | "@@bidi_start_edge" | "@@bidi_end_edge" | "actionTitle" | "connectionLabel" | "defaultPortLabel" | "enabledLabel" | "extDescription" | "extName" | "loadError" | "portLabel" | "popupWarningMatch" | "saveButton" | "saveFeedback" | "statusChecking" | "statusConnected" | "statusNotRunning",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
  }
}
